export const thoughtsArray = [
    "The best way to predict the future is to create it.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Don’t watch the clock; do what it does. Keep going.",
    "Believe you can and you're halfway there.",
    "Start where you are. Use what you have. Do what you can.",
    "Happiness is not by chance, but by choice.",
    "Don’t limit your challenges. Challenge your limits.",
    "It’s not whether you get knocked down; it’s whether you get up.",
    "Act as if what you do makes a difference. It does.",
    "Perseverance is not a long race; it's many short races one after the other.",
    "Dream big, start small, but most of all, start.",
    "Success usually comes to those who are too busy to be looking for it.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Don’t stop when you're tired; stop when you're done.",
    "Your limitation—it’s only your imagination.",
    "Great things never come from comfort zones.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "You don’t have to be great to start, but you have to start to be great.",
    "Small progress is still progress.",
    "Don’t wait for opportunity. Create it.",
    "Difficult roads often lead to beautiful destinations.",
    "The future depends on what you do today.",
    "You can’t change what’s going on around you until you start changing what’s going on within you.",
    "Go the extra mile. It’s never crowded.",
    "Dream it. Wish it. Do it.",
    "Success is a journey, not a destination.",
    "Good things come to those who hustle.",
    "The secret to getting ahead is getting started.",
    "You are braver than you believe, stronger than you seem, and smarter than you think.",
    "Don’t let yesterday take up too much of today.",
    "Make each day your masterpiece.",
    "Your only limit is your mind.",
    "Work hard in silence, let your success be your noise.",
    "Don't stop until you're proud.",
    "Sometimes later becomes never. Do it now.",
    "It’s never too late to be what you might have been.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Push yourself, because no one else is going to do it for you.",
    "You have to be at your strongest when you’re feeling at your weakest.",
    "If it doesn’t challenge you, it won’t change you.",
    "Believe in yourself and all that you are.",
    "The only place where success comes before work is in the dictionary.",
    "Your passion is waiting for your courage to catch up.",
    "You don’t have to be perfect to be amazing.",
    "Opportunities don’t happen, you create them.",
    "Do something today that your future self will thank you for.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Don’t be afraid to give up the good to go for the great.",
    "You are capable of more than you know.",
    "Stop doubting yourself, work hard, and make it happen.",
    "You can do anything you set your mind to.",
    "Dream bigger. Do bigger.",
    "A little progress each day adds up to big results.",
    "Your life does not get better by chance, it gets better by change.",
    "Success doesn’t just find you. You have to go out and get it.",
    "Start where you are. Use what you have. Do what you can.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "We may encounter many defeats but we must not be defeated.",
    "Do what you can with all you have, wherever you are.",
    "Don’t wait for the right opportunity: create it.",
    "Don’t wish for it. Work for it.",
    "In the middle of every difficulty lies opportunity.",
    "The key to success is to focus on goals, not obstacles.",
    "You are stronger than you think.",
    "Life is short. Live passionately.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "The only limit to your impact is your imagination and commitment.",
    "Turn your wounds into wisdom.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "If you're not willing to risk the usual, you'll have to settle for the ordinary.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "When you feel like quitting, think about why you started.",
    "Go confidently in the direction of your dreams.",
    "Doubt kills more dreams than failure ever will.",
    "Believe in the power of yet.",
    "You are never too old to set another goal or to dream a new dream.",
    "Strive for progress, not perfection.",
    "You don’t need to see the whole staircase, just take the first step.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
    "Whatever you are, be a good one.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "Success is stumbling from failure to failure with no loss of enthusiasm.",
    "A goal without a plan is just a wish.",
    "You are the artist of your own life. Don’t hand the paintbrush to anyone else.",
    "Your time is limited, don’t waste it living someone else’s life.",
    "You can’t go back and change the beginning, but you can start where you are and change the ending.",
    "Success isn’t about how much money you make. It’s about the difference you make in people’s lives.",
    "In a world where you can be anything, be kind.",
    "You are what you do, not what you say you'll do.",
    "Your greatest asset is your mindset.",
    "Do what you feel in your heart to be right—for you'll be criticized anyway.",
    "Don’t count the days. Make the days count.",
    "No one is perfect—that’s why pencils have erasers.",
    "Be so good they can’t ignore you.",
    "Success is not about being the best. It’s about always getting better.",
    "Great things never come from comfort zones.",
    "You miss 100% of the shots you don’t take.",
    "The harder the battle, the sweeter the victory.",
    "Don’t let anyone dull your sparkle.",
    "Success is getting what you want, happiness is wanting what you get.",
    "You can’t pour from an empty cup. Take care of yourself first.",
    "Learn from yesterday, live for today, hope for tomorrow.",
    "The only way to do great work is to love what you do.",
    "The journey of a thousand miles begins with one step.",
    "Every day may not be good, but there’s something good in every day.",
    "You are enough just as you are.",
    "Don’t wait for the perfect moment. Take the moment and make it perfect.",
    "Life is too short to wait.",
    "What defines us is how well we rise after falling.",
    "Be yourself; everyone else is already taken.",
    "Do what you love, and you’ll never work a day in your life.",
    "The best revenge is massive success.",
    "If it were easy, everyone would do it.",
    "Doubt kills more dreams than failure ever will.",
    "In order to succeed, we must first believe that we can.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Strength doesn’t come from what you can do. It comes from overcoming the things you once thought you couldn’t.",
    "Life is not about waiting for the storm to pass but learning to dance in the rain.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Hard times may have held you down, but they will not last forever.",
    "Even the darkest night will end, and the sun will rise again.",
    "What seems to us as bitter trials are often blessings in disguise.",
    "It’s not the load that breaks you down, it’s the way you carry it.",
    "Always do your best. What you plant now, you will harvest later.",
    "You don’t always need a plan. Sometimes you just need to breathe, trust, let go, and see what happens.",
    "Turn your can'ts into cans and your dreams into plans."
    // ... continue to add up to 300 thoughts
  ];
  

  